-- Restore the full coach biographies used by the public production modal.
UPDATE coaches AS coach
SET bio = roster.bio,
    updated_at = now()
FROM (
  VALUES
    ('Leo Rojas', 'COACH LEO is our Head of Player Development. He''s in charge of leading everything related to the preparation and execution of the lessons and programs. Has extensive experience in player development and his focus is not only on developing great players but also great kids. Leo was a professional catcher for the San Francisco Giants, playing in the different Minors levels of the organization for 4 years. He also has experience as a coach for the Giants, being one of the coaches of the organization''s academy in the Dominican Republic. Leo also had work experience within a player representation agency. Leo offers high level catching and hitting lessons to his players. In addition, his social media has incredible content. Follow him on @leobsbl.'),
    ('Santiago Chirino', 'Signed as an international free agent by the Texas Rangers in 2008, COACH CHI-CHI brings his 13 years of experience as a baseball professional player. He''s one of the most recent incorporation to our crew. He''s known as the Frontier League (MiLB) Hit King, since he has the hits and runs scored record in the history of the league, isn''t that cool? Santiago had a 1 year experience as an MiLB player-coach and have more that 4 years coaching young players. He''s got a lot of fresh coaching and player insights and is very motivated to start this new stage of his career as player development coach in Melbourne, FL. Follow Coach Santiago on his social media @santiagochirino.'),
    ('Raychel Trocki', 'Coach Raychel brings a wealth of experience and passion to our coaching team. A standout player at the Florida Institute of Technology from 2019-2021, Raychel has transitioned her on-field success into a dynamic coaching career, now with six years of experience under her belt. Her dedication to developing young talent is evident, with over 10 pitchers under her guidance having secured scholarships at various levels, ranging from Junior College to Division 1. Raychel''s coaching style is characterized by her deep knowledge of the game, her patience, and her genuine passion for helping young athletes grow both on and off the field. Follow Coach Raychel in Instagram: @coach.raychel.'),
    ('Kyle Huckaby', 'Coach Kyle knows what it takes to pitch at the next level, because he''s been there. A Division I arm at Eastern Michigan University (2014–2017) and record-setting closer at Benedictine University Mesa (AZ) in 2019, he signed with the Toronto Blue Jays that same year and spent the next 6 seasons on the pro mound. He''s also coached at the college level as the Pitching Coach for Christian Brothers University (D2, TN) and has worked one-on-one with pitchers for over 4 years, helping them throw harder, stay healthier, and dominate hitters. Follow him on Instagram @fluid_baseball.'),
    ('Tristen Carranza', 'Originally from El Centro, CA, moved to Brevard County after finishing his 4th professional season. Son of former Colorado Rockies, Pedro Carranza, COACH TRISTEN comes from a baseball family originally from Mexico. While in High School he was Drafted in the Mexican Winter League by the Aguilas de Mexicali and was offered to sign as a Free Agent with the Chicago Cubs in 2015 but decided to pursue his education. After his collegiate career came to an end he signed a free agent contract with the Arizona Diamondbacks where he was named a Pioneer League All-Star in 2019. He currently works in the New York Mets minor league system and is eager to help the next generation of players.'),
    ('José Bermúdez', 'Coach José was signed by the Atlanta Braves organization in 2016 and played professional ball for over six years. After his playing career, he dedicated himself to youth player development and has been coaching for the past four years, working with private clients and travel teams. He is passionate about discipline, hard work and helping players unlock their full potential.'),
    ('Melissa Martínez', 'COACH MELISSA played 4 years as a D1 softball player at Florida Atlantic University. She was an assistant coach for a summer ball travel team in 2017 and has been giving private softball lessons since 2020. She focuses in all-game aspects, specially in hitting and infield defense. She speaks both english and spanish. Follow Coach Melissa on her social media @xmelissaamartinez.'),
    ('Austin Dennis', 'Our guy from Rockledge, FL. COACH AUSTIN has been working with kids development since 2020, focusing on hitting, pitching and defense. He played OF, IF and pitched at Middle Tennessee State University. He was drafted in 2018 by the Houston Astros, played AAA for the organization and also AA for the KC Royals. He''s currently playing Independent ball. Follow Coach Austin on his social media @austindennis2.'),
    ('Jamie Gilbert', 'Former Division I pitcher at the University of Texas at San Antonio, where she accumulated more than 370 collegiate innings in the circle. Jamie brings extensive experience in pitcher development, helping athletes improve mechanics, command, velocity, and overall confidence on the mound. Her approach combines high-level playing experience with individualized instruction designed to help pitchers compete at their highest level.'),
    ('Gianmarco Marcelletti', 'Former college baseball player with ISSA certifications and over 5 years of experience training athletes, including college and MLB players.'),
    ('Rylan Thomas', 'Former Division I standout at University of Central Florida and professional player in the Cincinnati Reds system after being selected in the 2018 MLB Draft. Rylan was recognized as one of the top hitters in college baseball, earning All-Conference honors while setting multiple offensive records at UCF. He specializes in swing development, approach, power production, and helping hitters maximize their performance at the plate.'),
    ('Taylor Jensen', 'A two-time NJCAA National Champion at Florida SouthWestern State College, Taylor continued her collegiate career at UTSA, earning Second Team All-Conference honors while posting a .364 career batting average. With extensive experience behind the plate, she specializes in catching development, hitting instruction, and helping athletes build the skills and confidence needed to succeed at every level.')
) AS roster(name, bio)
WHERE trim(coach.name) = roster.name;